--DROP USER 'oauth-admin'@'localhost';
--DROP USER 'oauth-admin'@'%';
CREATE USER 'oauth-admin'@'localhost' IDENTIFIED BY 'oauthsecureP@ssw0rd';
GRANT ALL PRIVILEGES ON `oauthsecure`.* TO 'oauth-admin'@'localhost';
CREATE USER 'oauth-admin'@'%' IDENTIFIED BY 'oauthsecureP@ssw0rd';
GRANT ALL PRIVILEGES ON `oauthsecure`.* TO 'oauth-admin'@'%';
FLUSH PRIVILEGES;
CREATE SCHEMA `oauthsecure` DEFAULT CHARACTER SET utf8 ;

DROP TABLE IF EXISTS oauthsecure.OAUTH_CLIENT_GRANT_TYPES;
DROP TABLE IF EXISTS oauthsecure.OAUTH_CLIENT_RESPONSE_TYPES;
DROP TABLE IF EXISTS oauthsecure.OAUTH_CLIENT_SCOPES;
DROP TABLE IF EXISTS oauthsecure.OAUTH_CLIENT_REDIRECT_URIS;
DROP TABLE IF EXISTS oauthsecure.OAUTH_CLIENT_CONTACTS;
DROP TABLE IF EXISTS oauthsecure.OAUTH_CLIENT_SECRETS;
DROP TABLE IF EXISTS oauthsecure.OAUTH_CLIENTS;
DROP TABLE IF EXISTS oauthsecure.OAUTH_GRANT_TYPES;
DROP TABLE IF EXISTS oauthsecure.OAUTH_RESPONSE_TYPES;
DROP TABLE IF EXISTS oauthsecure.OAUTH_TOKEN_ENDPOINT_AUTH_METHODS;

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_GRANT_TYPES (
	TYPE_ID			VARCHAR(255) NOT NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	
	,PRIMARY KEY (TYPE_ID)
) CHARACTER SET utf8;

INSERT INTO oauthsecure.OAUTH_GRANT_TYPES(TYPE_ID) VALUES ('authorization_code');
INSERT INTO oauthsecure.OAUTH_GRANT_TYPES(TYPE_ID) VALUES ('implicit');
INSERT INTO oauthsecure.OAUTH_GRANT_TYPES(TYPE_ID) VALUES ('password');
INSERT INTO oauthsecure.OAUTH_GRANT_TYPES(TYPE_ID) VALUES ('client_credentials');
INSERT INTO oauthsecure.OAUTH_GRANT_TYPES(TYPE_ID) VALUES ('refresh_token');
INSERT INTO oauthsecure.OAUTH_GRANT_TYPES(TYPE_ID) VALUES ('urn:ietf:params:oauth:grant-type:jwt-bearer');
INSERT INTO oauthsecure.OAUTH_GRANT_TYPES(TYPE_ID) VALUES ('urn:ietf:params:oauth:grant-type:saml2-bearer');

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_RESPONSE_TYPES (
	TYPE_ID			VARCHAR(255) NOT NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	
	,PRIMARY KEY (TYPE_ID)
) CHARACTER SET utf8;

INSERT INTO oauthsecure.OAUTH_RESPONSE_TYPES(TYPE_ID) VALUES ('code');
INSERT INTO oauthsecure.OAUTH_RESPONSE_TYPES(TYPE_ID) VALUES ('token');

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_TOKEN_ENDPOINT_AUTH_METHODS (
	TYPE_ID			VARCHAR(255) NOT NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	
	,PRIMARY KEY (TYPE_ID)
) CHARACTER SET utf8;

INSERT INTO oauthsecure.OAUTH_TOKEN_ENDPOINT_AUTH_METHODS(TYPE_ID) VALUES ('none');
INSERT INTO oauthsecure.OAUTH_TOKEN_ENDPOINT_AUTH_METHODS(TYPE_ID) VALUES ('client_secret_post');
INSERT INTO oauthsecure.OAUTH_TOKEN_ENDPOINT_AUTH_METHODS(TYPE_ID) VALUES ('client_secret_basic');

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_CLIENTS (
	CLIENT_ID			VARCHAR(255) NOT NULL
	,CLIENT_NAME		VARCHAR(512) NOT NULL
	,CLIENT_URI			VARCHAR(4096) NULL
	,LOGO_URI			VARCHAR(4096) NULL
	,TOS_URI			VARCHAR(4096) NULL
	,POLICY_URI			VARCHAR(4096) NULL
	,JWKS_URI			VARCHAR(4096) NULL
	,SOFTWARE_ID		VARCHAR(255) NULL
	,SOFTWARE_VERSION	VARCHAR(100) NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 	,LAST_UPDATED_ON	TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
	
	,PRIMARY KEY (CLIENT_ID)
	,UNIQUE(SOFTWARE_ID)
) CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_CLIENT_SECRETS (
	CLIENT_ID			VARCHAR(255) NOT NULL
	,CLIENT_SECRET		VARCHAR(255) NOT NULL
	,EXPIRES_ON			DATETIME NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 	,LAST_UPDATED_ON	TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
	
	,PRIMARY KEY (CLIENT_ID)
	,FOREIGN KEY (CLIENT_ID) REFERENCES OAUTH_CLIENTS(CLIENT_ID)
	,UNIQUE (CLIENT_SECRET)
) CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_CLIENT_SCOPES (
	ID					BIGINT NOT NULL AUTO_INCREMENT
	,CLIENT_ID			VARCHAR(255) NOT NULL
	,SCOPE				VARCHAR(255) NOT NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 	,LAST_UPDATED_ON	TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
	
	,PRIMARY KEY (ID)
	,FOREIGN KEY (CLIENT_ID) REFERENCES OAUTH_CLIENTS(CLIENT_ID)
) CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_CLIENT_REDIRECT_URIS (
	ID					BIGINT NOT NULL AUTO_INCREMENT
	,CLIENT_ID			VARCHAR(255) NOT NULL
	,REDIRECT_URI		VARCHAR(4096) NOT NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 	,LAST_UPDATED_ON	TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
	
	,PRIMARY KEY (ID)
	,FOREIGN KEY (CLIENT_ID) REFERENCES OAUTH_CLIENTS(CLIENT_ID)
) CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_CLIENT_CONTACTS (
	ID					BIGINT NOT NULL AUTO_INCREMENT
	,CLIENT_ID			VARCHAR(255) NOT NULL
	,EMAIL_ADDRESS		VARCHAR(4096) NOT NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 	,LAST_UPDATED_ON	TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
	
	,PRIMARY KEY (ID)
	,FOREIGN KEY (CLIENT_ID) REFERENCES OAUTH_CLIENTS(CLIENT_ID)
) CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_CLIENT_GRANT_TYPES (
	ID					BIGINT NOT NULL AUTO_INCREMENT
	,CLIENT_ID			VARCHAR(255) NOT NULL
	,GRANT_TYPE_ID		VARCHAR(255) NOT NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 	,LAST_UPDATED_ON	TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
	
	,PRIMARY KEY (ID)
	,FOREIGN KEY (CLIENT_ID) REFERENCES OAUTH_CLIENTS(CLIENT_ID)
	,FOREIGN KEY (GRANT_TYPE_ID) REFERENCES OAUTH_GRANT_TYPES(TYPE_ID)
) CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS oauthsecure.OAUTH_CLIENT_RESPONSE_TYPES (
	ID					BIGINT NOT NULL AUTO_INCREMENT
	,CLIENT_ID			VARCHAR(255) NOT NULL
	,RESPONSE_TYPE_ID	VARCHAR(255) NOT NULL
	
	,CREATED_ON		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
 	,LAST_UPDATED_ON	TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
	
	,PRIMARY KEY (ID)
	,FOREIGN KEY (CLIENT_ID) REFERENCES OAUTH_CLIENTS(CLIENT_ID)
	,FOREIGN KEY (RESPONSE_TYPE_ID) REFERENCES OAUTH_RESPONSE_TYPES(TYPE_ID)
) CHARACTER SET utf8;
